name: typescript-language-server
version: 4.3.3
summary: Typescript Language Server
description: |
  Language Server Protocol implementation for TypeScript wrapping tsserver.

grade: stable
confinement: strict
base: core20
issues: https://github.com/alexmurray/typescript-language-server-snap/issues
website: https://github.com/typescript-language-server/typescript-language-server

apps:
  typescript-language-server:
    command: bin/node $SNAP/bin/typescript-language-server
    plugs:
      - home

parts:
  typescript-language-server:
    plugin: npm
    source: https://github.com/typescript-language-server/typescript-language-server.git
    source-tag: v$SNAPCRAFT_PROJECT_VERSION
    build-environment:
      - NODEJS_VERSION: "v22.13.0"
    npm-node-version: $NODEJS_VERSION
    override-build: |
      # install the official nodejs so we get the expected npm version
      if [ $SNAP_ARCH == "amd64" ]; then
        ARCH=x64
      elif [ $SNAP_ARCH == "armhf" ]; then
        ARCH=armv7l
      elif [ $SNAP_ARCH == "ppc64el" ]; then
        ARCH=ppc64le
      else
        ARCH=$SNAP_ARCH
      fi
      curl -s https://nodejs.org/dist/"${NODEJS_VERSION}"/node-"${NODEJS_VERSION}"-linux-$ARCH.tar.gz | tar xzf - -C "$SNAPCRAFT_PART_INSTALL" --strip-components=1
      npm install -g yarn
      yarn install
      yarn build
      yarn global add --prefix $SNAPCRAFT_PART_INSTALL $(yarn pack . | grep "Wrote tarball to" | cut -f2 -d'"')
      # install typescript manually as a dependency
      yarn global add --prefix $SNAPCRAFT_PART_INSTALL typescript
      # fixup install location to avoid symlinks pointing outside the snap
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/local/share/.config
      mv /usr/local/share/.config/yarn $SNAPCRAFT_PART_INSTALL/usr/local/share/.config
      for bin in typescript-language-server tsc tsserver; do \
        rm -f $SNAPCRAFT_PART_INSTALL/bin/$bin; \
        ln -s ../usr/local/share/.config/yarn/global/node_modules/.bin/$bin $SNAPCRAFT_PART_INSTALL/bin/$bin; \
      done
